name: CI

on: push

jobs:
  build:
    name: Tutorial Testing on Linux
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Testing OpenAQ
        run: ./scripts/tutorial_test.sh
